version: '2'

volumes:
  traveling_disk:

services:
  traveler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8789:8789
      - 8000:8000
    volumes:
      - traveling_disk:/traveler-integrated
